---
  - name: Provisioning an Elastic Load Balancer
    ec2_elb_lb:
      name: "WebApp-ELB"
      state: present
      tags:
        Name: WebApp-ELB
        Region: "{{ ec2_region }}"
        Environment: "Testing"
      security_group_names: my-sec-grp
