---
  # This role helps provision an ec2 instance of t2.micro type
 - name: Provision an ec2 instance
   ec2:
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image_id }}"
      region: "{{ ec2_region }}"
      wait: yes
      wait_timeout: 500
      count: "{{ ec2_instance_count }}"
      group: "{{ ec2_group }}"
      instance_tags:
        Name: "{{ ec2_inst_name }}"
        Environment: "Testing"
      volumes:
        - device_name: /dev/xvda
          volume_type: "{{ ec2_vol_type }}"
          volume_size: "{{ ec2_vol_size }}"
          delete_on_termination: true
